### ISSUE TITLE
Cannot build on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by nicolasf** [htrefil/rkvm#28]
Due to OpenSSL version differences, the rust compiler can't build against a default Ubuntu 22.04 installation with openssl installed.

Solution is to update openssl and openssl-sys dependencies of the project.

**Comment by Omrigan** [comment]
What is the error you get? I have something like 
`"RUST_VERSION_OPENSSL_" and "(" does not give a valid preprocessing token` 
on Arch. 

For me, `cargo update` also seems to work.

**Comment by htrefil** [comment]
This is fixed, a new release will be out soon. rkvm will no longer depend on openssl.
