### ISSUE TITLE
Enter key not working when software is running

### ISSUE THREAD

**Issue by beniwtv** [htrefil/rkvm#3]
Great little tool!

I have one small issue: As soon as I start the server, my enter key stops working. I can see that in the console, the output is scrolling, as if the enter key is always pressing down.

**Comment by beniwtv** [comment]
I should add that when started via systemctl service, this does not happen.

**Comment by htrefil** [comment]
Hello, this looks like some race condition issue where rkvm grabs the keyboard and doesn't register the enter key release event and thus doesn't propagate it further. I think this could be mitigated by adding a short sleep before input devices are grabbed.

I don't have access to my computer right now, could you please check if it works by adding a `time::sleep_for(Duration::from_millis(500)).await` before the /dev/input directory is traversed and devices grabbed in input/src/event_manager.rs?

**Comment by beniwtv** [comment]
Hey, yep, that worked. I could no longer reproduce this.

**Comment by htrefil** [comment]
Fixed in commit e7984e1.
