### ISSUE TITLE
Mouse scrolling issue

### ISSUE THREAD

**Issue by skiby7** [htrefil/rkvm#32]
Everything seems to work just fine except the wheel scrolling: when I switch to a client and I scroll with mouse wheel, the server receives the input, too.

I'm on Fedora 37 with Gnome 43 on Wayland.
Also, to make it work I followed what's reported [here](https://github.com/htrefil/rkvm/issues/15#issuecomment-1302822790)

**Comment by htrefil** [comment]
Fixed - this was caused by not understanding the EV_WHEEL_HI_RES event. This will be put out in a new release shortly.

**Comment by faassen** [comment]
Is this supposed to be fixed in the repository? Because I just installed fresh on server and client from the repository and mouse wheel scrolling doesn't work on the client.
