### ISSUE TITLE
[Windows Support] Can't Compile, Also No Instructions

### ISSUE THREAD

**Issue by Unhall0w3d** [htrefil/rkvm#35]
It appears that Windows support was added back in 0.2.x but the ReadMe was not updated with such instructions. Attempting to compile on Windows leads to a failure compiling inotify-sys due to issues with 'libc'. 

```
error[E0425]: cannot find value 'O_CLOEXEC' in crate 'libc'
error[E0425]: cannot find value 'O_NONBLOCK' in crate 'libc'
could not compile 'inotify-sys' due to 2 previous errors
build failed, waiting for other jobs to finish...
```

If Windows is supported, what is the documented steps from the Windows (Client) side?

**Comment by htrefil** [comment]
Sorry, Windows is not supported anymore, the client support was rudimentary anyway.
