### ISSUE TITLE
IPv6 server config (ie. on the client side) reading fails

### ISSUE THREAD

**Issue by JPenuchot** [htrefil/rkvm#40]
Hi,

I've been trying to configure RKVM to work over IPv6 but I can't specify a server address on the client side. I wrote the IPv6 address in the `[1234:1234:2134::]:5258` format, and I see your parsing function splits using `:` as a separator. I suspect that's why IPv6 addresses aren't parsed correctly in the configuration.

Regards,
Jules

**Comment by htrefil** [comment]
Can you show me the specific error please?

**Comment by htrefil** [comment]
Fixed in e401fee.

**Comment by JPenuchot** [comment]
Thank you!
