### ISSUE TITLE
switch keys remain pressed

### ISSUE THREAD

**Issue by jimdigriz** [htrefil/rkvm#42]
I use `rkvm` (ec11f26c9041542cba75e55158f122c4a31a7fdb) between my desktop (server) and laptop (client) and if I have recently toggled from the laptop back to the desktop the switch keys remain active on the client. This means whilst this is occuring, any attempt to use the physical keyboard on the laptop, those proxied keys are still active too.

I am sticking with the defaults (`switch-keys = ["LeftAlt", "LeftCtrl"]`) and by running `evtest` on the client as you do the switch the value of the key(s) remains set to one (ie. pressed).

Maybe return the switch keys back to a unset state after a switch is the solution here?

**Comment by htrefil** [comment]
Thanks for reporting this! Fixed in ad4d362.
