### ISSUE TITLE
Donation ?

### ISSUE THREAD

**Issue by JPenuchot** [htrefil/rkvm#47]
Hey,

rkvm works brilliantly since the last update. It has no issue with trackpads anymore and even gestures work perfectly!

Is there any way I can make a donation? You solved a big headache of mine since input-leap isn't compatible with Sway, and your solution also works with login screens.

Many many thanks

**Comment by htrefil** [comment]
Hello! I'm very happy to hear that rkvm solves your problems as well as mine.

To be honest, I never counted with accepting donations for this project, but I guess I'd be stupid to refuse them - so based on your suggestion, I created and added my [Ko-fi page](https://ko-fi.com/htrefil) to the project's README and Github funding file.

Thanks!
