### ISSUE TITLE
implement pkg-config support so that rkvm can be packaged for nix/nixpkgs

### ISSUE THREAD

**Issue by colemickens** [htrefil/rkvm#6]
Hi!

I am trying to package this with `nix` for nixpkgs: https://github.com/NixOS/nixpkgs/issues/108276

However, the inner `input` crate fails to build because it can't find evdev. Using pkg-config will solve this issue.

**Comment by htrefil** [comment]
Hi, sorry for the late response! Fixed by using the pkg-config crate in `input`s build script.
