### ISSUE TITLE
Keybindings to Switch Multiple Screens

### ISSUE THREAD

**Issue by g-h-97** [htrefil/rkvm#67]
Hi,

I'm not sure if this exists on not due to lack of documentation. But can switching screens with multiple key binding be implemented ?

For now I can only see `switch-keys` which only rotates screens. I'd be great if we can switch to specific screen using bindings such as `left-alt, left-shift, 1` for 1st screen ...etc

Also thanks for the great project :) it solved a lot of issue I was having with synergy/barrier. Thank you kindly, I'll make sure to donate ASAP,

**Comment by htrefil** [comment]
Hey,
this is not possible right now as rkvm-server doesn't know clients in advance.

I don't think this would be hard to implement if we make clients send their hostname (or other identification) and extend the server config.

Unfortunately I'm busy with work, so I don't have much time to implement it myself. That being said, I'll gladly accept a PR implementing it.
