### ISSUE TITLE
Mouse Pass Screen Border

### ISSUE THREAD

**Issue by g-h-97** [htrefil/rkvm#68]
Hi,

Is there a technical reason as of why mouse can't pass screen borders ? like barrier for example

**Comment by rolflobker** [comment]
`rkvm` has no knowledge about screens or borders
It redirects input, that's it.

This is one of the reason why this works regardless of which displaymanager you're using
And it's the main reason why I just set it up and am loving it.

**Comment by g-h-97** [comment]
@rolflobker got it, appreciate the explanation.
