### ISSUE TITLE
Shared Clipboard

### ISSUE THREAD

**Issue by g-h-97** [htrefil/rkvm#69]
Hi,

I think it's really useful to have the clipboard shared between multiple machines, is the lack of this due a technical limitation in order guarantee cross compatibility ? or is it possible ?

**Comment by netizen-ais** [comment]
IMHO, while it's true that clipboard sharing would be a useful thing, it's completely out of the scope of this project.

**Comment by g-h-97** [comment]
Hi @netizen-ais ,

Thanks for the response, I see. You're going for Unix approach ;)

The issue is that there is no too for "Unixy" tool for clipboard sharing that's clean and open source, any ideas ?

**Comment by netizen-ais** [comment]
You're right about my Unix philosophy approach, @g-h-97. A quick search gave me a couple of tools:

- https://github.com/trueaniki/shared-clipboard (LGTM)
- https://github.com/zachhuff386/clipsync (Maybe X11 only)

**Comment by g-h-97** [comment]
I really appreciate the suggestions @netizen-ais .

It seems that `shared-clipboard` is a relatively new project and it doesn't support encryption which is deal breaker for me. However, `clipsync` seems really promising TBF.

I also found an AUR package while looking for `clipsync` :) 

It's `clipboard-sync` which seems suspiciously similar, although, it's written in rust which makes it that much more interesting (I think it does not support encryption)

**Comment by netizen-ais** [comment]
The latest one (rust) is not for network usage, just localhost, if I did read correctly, but I was wrong about clipsync being X11 only

**Comment by g-h-97** [comment]
Yup, I just realized this. I realize this I finally settled with `uniclip`.
