### ISSUE TITLE
add `[[bin]] name` to Cargo.toml to output prefixed executables

### ISSUE THREAD

**Issue by colemickens** [htrefil/rkvm#8]
In the course of packaging this, I noticed that the built binaries are called `client`, `server`, and `certificate-gen`.

For my Nix derivation, I simply prefix them all with `rkvm-` but I'm wondering if it would be more appropriate to just fix this in the various binaries' `Cargo.toml` files so that they're automatically named with a prefix.

What do you think?

**Comment by colemickens** [comment]
I forgot, the other reason this would be nice, I could add the same GitHub action that I added for another Rust project and you'd get Windows binaries attached to a GHA job for each commit. That way you can get more Windows users without them having to build it.

**Comment by BrendanBall** [comment]
This is also the case for `cargo install --path server`. It ends up putting a binary called `server` on your path. So I also think it would be great to rename it. I'm not sure if @htrefil might be more responsive if you just open a PR and see what he says

**Comment by htrefil** [comment]
Fixed.
